Add generate scripts to main branch
cypress-io/cypress-component-testing-examples pull request #35
Opened 2021-10-13 20:37 UTC by kevinold

- Migrate generate scripts from `scripts` branch into folder in `main` branch
- Update README's to point to `main/scripts`

2021-10-13 20:39 UTC, kevinold commented
@cowboy Rather than regenerating the projects, I just did a find and replace to update the footer links to the script directory that is now present in the main branch.

2021-10-14 15:06 UTC, cowboy requested changes

2021-10-14 16:14 UTC, cowboy requested changes

2021-10-14 16:14 UTC, cowboy commented on scripts/global/pr_footer.md
> +_This example was generated by [${SCRIPT}](${REPO_URL}/blob/scripts/${SCRIPT}) on ${DATE}. The original README follows._
Well, keep _this_ change so we get the updated locations whenever we update any examples!

2021-10-14 17:04 UTC, merged