Vue CLI 2 & 3 Cypress Code Coverage Scripts
cypress-io/cypress-component-testing-examples pull request #51
Opened 2021-11-05 22:16 UTC by kevinold

2021-12-06 17:00 UTC, cowboy requested changes

2021-12-06 17:00 UTC, cowboy commented on scripts/vue-cli-2/3.patch
> ++++ b/vue-cli-2/src/components/Counter.vue
Missing the corresponding `Counter.spec.ct.js` spec file

2021-12-06 17:33 UTC, cowboy requested changes
x

2021-12-07 16:59 UTC, kevinold commented on scripts/vue-cli-3/3.patch
> +diff --git a/vue-cli-3/src/components/CounterComp.spec.ct.js b/vue-cli-3/src/components/CounterComp.spec.ct.js
@cowboy Regarding the name of `CounterComp.vue` in the Vue 3 CLI example — it is using the Vue 3 Component syntax vs the traditional.  In this example I am shipping the Vue 2 syntax in `Counter.vue`, so wonder what your thoughts are for naming the Vue 3 component?

2021-12-07 18:26 UTC, kevinold commented
@cowboy Updates made per notes and sync for Vue 2 and Vue 3 CLI's.  The associated PRs #52 #55 have been updated with the latest from the scripts.

2021-12-07 22:12 UTC, cowboy requested changes

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-2/pr.md
> +   4. Add [src/App.spec.ct.js](src/App.spec.ct.js), [src/components/HelloWorld.spec.ct.js](src/components/HelloWorld.spec.ct.js), [src/Counter.vue](src/Counter.vue), [src/components/Counter.spec.ct.j
Can you split this up into 2 lines, eg.

```suggestion
   1. Update [src/App.vue](src/App.vue) to reference new [src/components/Counter.vue](src/components/Counter.vue) component
   1. Add [src/App.spec.ct.js](src/App.spec.ct.js), [src/components/HelloWorld.spec.ct.js](src/components/HelloWorld.spec.ct.js), [src/components/Counter.spec.ct.js](src/components/Counter.spec.ct.js) spec files
```

Also, FWIW using `1.` for every bullet point means you won't ever have to re-number them.

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-2/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-2/pr.md
> +   6. Add [.nycrc](.nycrc)
Can you add a short bit of text to explain what this file is? Eg.

```suggestion
   6. Add [.nycrc](.nycrc) to configure istanbul
```

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-3/pr.md
> +   4. Add [src/App.spec.ct.js](src/App.spec.ct.js), [src/components/HelloWorld.spec.ct.js](src/components/HelloWorld.spec.ct.js), [src/Counter.vue](src/Counter.vue), [src/components/Counter.spec.ct.j
Split into 2 lines?

```suggestion
   1. Update [src/App.vue](src/App.vue) to reference new [src/components/Counter.vue](src/components/Counter.vue) component
   1. Add [src/App.spec.ct.js](src/App.spec.ct.js), [src/components/HelloWorld.spec.ct.js](src/components/HelloWorld.spec.ct.js), [src/components/Counter.spec.ct.js](src/components/Counter.spec.ct.js) spec files
```

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-3/pr.md
> +   5. Add [src/CounterCompositionApi.vue](src/components/CounterCompositionApi.vue), a Composition API component and test in [src/components/CounterCompositionApi.spec.ct.js](src/components/CounterCo
```suggestion
   5. Add [src/CounterCompositionApi.vue](src/components/CounterCompositionApi.vue), a Composition API component with tests in [src/components/CounterCompositionApi.spec.ct.js](src/components/CounterCompositionApi.spec.ct.js)
```

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-3/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-07 22:12 UTC, cowboy commented on scripts/vue-cli-3/pr.md
> +   6. Add [.nycrc](.nycrc)
Same comment as the other readme

2021-12-07 22:16 UTC, kevinold commented on scripts/vue-cli-3.sh
> +commit_all "Configure Cypress Code Coverage plugin and add additional component tests"
Good catch, adjusting and updating.

2021-12-07 22:18 UTC, kevinold commented on scripts/vue-cli-3/pr.md
> +   6. Add [.nycrc](.nycrc)
```suggestion
   6. Add [.nycrc](.nycrc)  to configure istanbul
```

2021-12-07 22:44 UTC, kevinold commented on scripts/vue-cli-3.sh
> +commit_all "Configure Cypress Code Coverage plugin and add additional component tests"
```suggestion
commit_all "Configure Cypress Code Coverage plugin"
```

2021-12-07 22:45 UTC, kevinold commented on scripts/vue-cli-2.sh
> +commit_all "Configure Cypress Code Coverage plugin and add additional component tests"
```suggestion
commit_all "Configure Cypress Code Coverage plugin"
```

2021-12-07 22:51 UTC, kevinold commented
@cowboy Updates made per notes and sync for Vue 2 and Vue 3 CLI's. The associated PRs #52 #55 have been updated with the latest from the scripts.

2021-12-13 20:04 UTC, cowboy approved these changes
LGTM. One question: what if the vue-cli-3 example just had a composition API Counter component and not the old type, since the vue-cli-2 example has the old type or component? I'm also ok with this as-is, I just want to make sure we're keeping it simple wherever possible.

2021-12-14 15:13 UTC, merged