Create React App Cypress Code Coverage Scripts
cypress-io/cypress-component-testing-examples pull request #62
Opened 2021-12-02 22:10 UTC by kevinold

For UNIFY-74

2021-12-06 16:17 UTC, cowboy requested changes
Overall, looks great, but I caught a few typos that will require having to re-generate PRs #63 #64 #65 #66 #67

One general note: should we add a bullet point to each "Add Cypress Code Coverage" section about modifying the `.gitignore` file? If we think that's important, I'd like to include it.

Also, can you use the generated "PR BODY" from the script somewhere in your PR, so it's easier to click into the generated README for review? Doing that might help us catch typos like the ones I noticed in this review!

2021-12-06 16:17 UTC, cowboy commented on scripts/create-react-app/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-06 16:17 UTC, cowboy commented on scripts/create-react-app-react-router/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-06 16:17 UTC, cowboy commented on scripts/create-react-app-redux/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-06 16:17 UTC, cowboy commented on scripts/create-react-app-tailwind/pr.md
> +   4. Edit [cypress/support/commands.js](cypress/support/commands.js) to import Cypress code coverage support
```suggestion
   4. Edit [cypress/support/index.js](cypress/support/index.js) to import Cypress code coverage support
```

2021-12-06 22:12 UTC, kevinold commented
@cowboy Per slack conversation, the CRA scripts are updated https://github.com/cypress-io/cypress-component-testing-examples/pull/62/commits/acfe99271aade2ef334c49652e8cfb309101349a and PRs #63 #64 #65 #66 #67 re-generated

2021-12-07 20:58 UTC, cowboy approved these changes

2021-12-07 21:07 UTC, merged